### ISSUE TITLE
--check should check to see if a entity reference field has a vocabulary (or other entity) configured

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#140]
If an entity field doesn't have any vocabularies configured, workbench pukes:

```
Traceback (most recent call last):
  File "./workbench", line 739, in <module>
    create()
  File "./workbench", line 110, in create
    row[custom_field] = prepare_term_id(config, field_vocabs, row[custom_field])
  File "/home/mark/Documents/hacking/workbench/workbench_utils.py", line 1198, in prepare_term_id
    if len(vocab_ids) == 1:
TypeError: object of type 'bool' has no len()
```

`--check` should check for this, tell the user, and exit. `get_field_vocabularies()` is probably where we want to check for referenced vocabularies.

**Comment by mjordan** [comment]
Resolved for vocabularies.
