### ISSUE TITLE
TypeError: string indices must be integers during --check of CSV used before

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#294]
I just tried doing an import of a CSV I've imported before without issue, and am getting this error during the --check:
```
Traceback (most recent call last):
  File "./workbench", line 953, in <module>
    check_input(config, args)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 1028, in check_input
    warn_user_about_taxo_terms = validate_taxonomy_field_values(config, field_definitions, validate_taxonomy_field_csv_data)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 2885, in validate_taxonomy_field_values
    terms = get_term_pairs(config, vocabulary)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 2131, in get_term_pairs
    name = term['name'][0]['value']
TypeError: string indices must be integers
```
I should note I did not pull the most recent version of Workbench before starting (but I've been running this one without issue for a while).

I have imported this CSV just fine in the past. CSV attached.
Thanks!
[i8_SampleIngestSheet_08.csv](https://github.com/mjordan/islandora_workbench/files/6717548/i8_SampleIngestSheet_08.csv)

**Comment by dara2** [comment]
When I originally saw this, I was not in main. So I moved to main and retested and am still getting the error.

Confirming I'm in main and pulled the latest - here's the output starting with when I first checked out main and there were changes, so I stashed them and then did a pull (hopefully I did that right):
```
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ git checkout main
M	add_media.yml
M	update.yml
Previous HEAD position was 90153a4 Resolves #273.
Switched to branch 'main'
Your branch is behind 'origin/main' by 33 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ git stash
Saved working directory and index state WIP on main: e65db45 Fixed comparison operator.
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ git checkout main
Already on 'main'
Your branch is behind 'origin/main' by 33 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ git pull origin main
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 50 (delta 31), reused 41 (delta 22), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/mjordan/islandora_workbench
 * branch            main       -> FETCH_HEAD
   90153a4..74a496e  main       -> origin/main
Updating e65db45..74a496e
Fast-forward
 README.md                                                        |  26 ++++
 create_from_files.yml                                            |  24 +---
 entity_post_task.yml                                             |   7 ++
 scripts/entity_post_task_example.py                              |  23 ++++
 tests/assets/create_from_files_test/create.yml                   |  10 +-
 tests/assets/execute_post_action_entity_script_test/create.yml   |   7 ++
 tests/assets/execute_post_action_entity_script_test/metadata.csv |   3 +
 tests/assets/execute_post_action_entity_script_test/rollback.yml |   6 +
 tests/assets/execute_post_action_entity_script_test/script.py    |  15 +++
 tests/islandora_tests.py                                         |  51 +++++++-
 tests/unit_tests.py                                              |  62 +++++-----
 workbench                                                        | 144 ++++++++++++---------
 workbench_utils.py                                               | 570 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------
 13 files changed, 643 insertions(+), 305 deletions(-)
 create mode 100644 entity_post_task.yml
 create mode 100755 scripts/entity_post_task_example.py
 create mode 100644 tests/assets/execute_post_action_entity_script_test/create.yml
 create mode 100644 tests/assets/execute_post_action_entity_script_test/metadata.csv
 create mode 100644 tests/assets/execute_post_action_entity_script_test/rollback.yml
 create mode 100755 tests/assets/execute_post_action_entity_script_test/script.py
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ git branch
  issue-227
  issue-265
  issue-77
* main
  master
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ ./workbench --config i8demo_Whitman/create.yml --check
OK, connection to Drupal at https://arminda-i8-prod.whitman.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file i8demo_Whitman/i8_SampleIngestSheet_08.csv found.
OK, all 12 rows in the CSV file have the same number of columns as there are headers (18).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, link field values in the CSV file validate.
OK, ETDF field values in the CSV file validate.
Traceback (most recent call last):
  File "./workbench", line 953, in <module>
    check_input(config, args)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 1023, in check_input
    warn_user_about_taxo_terms = validate_taxonomy_field_values(config, field_definitions, validate_taxonomy_field_csv_data)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 2935, in validate_taxonomy_field_values
    terms = get_term_pairs(config, vocabulary)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 2196, in get_term_pairs
    name = term['name'][0]['value']
TypeError: string indices must be integers
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$
```

**Comment by dara2** [comment]
Hi @mjordan - this is all set now! @ajstanley found that we needed to update the Terms in Vocabulary view so that "json" was selected in Serializer > Settings.
Perhaps this is now in the integration module and I just haven't updated the module. We made the config update manually in Drupal.

**Comment by mjordan** [comment]
OK, thanks. Yes, Workbench uses the json serialization to it must be available in the View.
