### ISSUE TITLE
AttributeError: 'CachedHTTPResponse' object has no attribute '__attrs_init__'

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#380]
nat@LIB-6HSWM53:~/tools/iw_3feb2022/islandora_workbench$ git log -1
commit 51fb86b8089e9d2f1517346cc5d75526580f1402 (HEAD -> main, origin/main, origin/HEAD)
Merge: 7cac972 6ff4a09
Author: Mark Jordan <mjordan@sfu.ca>
Date:   Sun Jan 30 15:32:46 2022 -0800

```
    Merge branch 'config_refactor' into main
nat@LIB-6HSWM53:~/tools/iw_3feb2022/islandora_workbench$ ./workbench --config create4.yml --check
OK, connection to Drupal at https://islandora.traefik.me verified.
Traceback (most recent call last):
  File "./workbench", line 1088, in <module>
    check_drupal_core_version(config)
  File "/home/nat/tools/iw_3feb2022/islandora_workbench/workbench_utils.py", line 250, in check_drupal_core_version
    drupal_core_version = get_drupal_core_version(config)
  File "/home/nat/tools/iw_3feb2022/islandora_workbench/workbench_utils.py", line 237, in get_drupal_core_version
    response = issue_request(config, 'GET', url)
  File "/home/nat/tools/iw_3feb2022/islandora_workbench/workbench_utils.py", line 124, in issue_request
    response = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/session.py", line 115, in request
    return super().request(method, url, headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/session.py", line 147, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/session.py", line 193, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/backends/base.py", line 95, in save_response
    cached_response = CachedResponse.from_response(response, expires=expires)
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/models/response.py", line 59, in from_response
    obj = cls(expires=expires, **kwargs)
  File "<attrs generated init requests_cache.models.response.CachedResponse>", line 30, in __init__
  File "/usr/local/lib/python3.8/dist-packages/requests_cache-0.9.0-py3.8.egg/requests_cache/models/raw_response.py", line 36, in __init__
    self.__attrs_init__(*args, **kwargs)
AttributeError: 'CachedHTTPResponse' object has no attribute '__attrs_init__'
```

**Comment by Natkeeran** [comment]
Thank you @ajstanley  for helping troubleshoot this.

Even though I ran the `sudo python3 setup.py install` and it ran without issues, looks like I did not have  requests_cache library.  Installing that library resolved this issue.  Perhaps, this can be added as a troubleshooting step (i.e verify you have all the libs needed in the setup.py).

I've ran into this issue before as well, when trying to setup a docker image with workbench as below.  Running setup was not sufficient, needed to have the libraries installed by pip.  


```
FROM alpine

RUN apk add \
        build-base \
        bash \
        git \
        git-lfs \
        python3 \
        python3-dev \
        gcc \
        py3-pip

RUN pip install progress_bar openpyxl ruamel.yaml unidecode edtf_validate

RUN  mkdir WORK_REPO
RUN  cd  WORK_REPO
WORKDIR  /WORK_REPO
RUN git clone https://github.com/mjordan/islandora_workbench

WORKDIR "/WORK_REPO/islandora_workbench"
CMD ["python3", "setup.py", "install"]

RUN git lfs clone https://github.com/kstapelfeldt/repo_islandora_demo_objects

ADD create_sample_objects.yml .

CMD ["python3", "workbench", "--config", "create_sample_objects.yml"]
```
