### ISSUE TITLE
Error with preprocessed_file_path = get_prepocessed_file_path(config, file_fieldname, csv_row)

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#391]
I was running into an issue during --check using the latest version of Workbench (updated Friday).

Excerpt from my terminal:
```
OK, files named in the CSV "file" column are all present; the "allow_missing_files" option is enabled and empty "file" values exist.
Traceback (most recent call last):
  File "./workbench", line 1113, in <module>
    check_input(config, args)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 1203, in check_input
    media_type = set_media_type(config, file_check_row[filename_field], filename_field, file_check_row)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 46, in set_media_type
    preprocessed_file_path = get_prepocessed_file_path(config, file_fieldname, csv_row)
TypeError: get_prepocessed_file_path() missing 1 required positional argument: 'node_id'
islandora@islandora01:~/islandora_workbench$
```
I talked with @ajstanley and he gave me one line to fix this. I made the edit and can confirm it works! 
Alan said:

> Try going to line 4124 in workbench_utils.py and adding a default argument value -

```
def get_prepocessed_file_path(config, file_fieldname, node_csv_row, node_id = None):
```

**Comment by mjordan** [comment]
Fix merged.
