### ISSUE TITLE
User warning: fopen(): No such file or directory in Twistor\FlysystemStreamWrapper->triggerError()

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#408]
When ingesting or running add_media, I'm seeing a lot of these PHP warnings in the Drupal log. I am in Drupal 9.3.3. Is this an issue related to Workbench or to our site?

```
Type	php
Date	Monday, April 11, 2022 - 18:53
User	admin
Location	https://digitalcollections-prod.saic.edu/node/34230/media/image/8
Referrer	
Message	User warning: fopen(): No such file or directory in Twistor\FlysystemStreamWrapper->triggerError() (line 921 of /var/www/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php)
#0 /var/www/drupal/web/core/includes/bootstrap.inc(346): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /var/www/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php(921): trigger_error()
#3 /var/www/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php(899): Twistor\FlysystemStreamWrapper->triggerError()
#4 /var/www/drupal/vendor/twistor/flysystem-stream-wrapper/src/FlysystemStreamWrapper.php(512): Twistor\FlysystemStreamWrapper->invoke()
#5 [internal function]: Twistor\FlysystemStreamWrapper->stream_open()
#6 /var/www/drupal/web/modules/contrib/filehash/filehash.module(209): hash_file()
#7 /var/www/drupal/web/modules/contrib/filehash/filehash.module(53): filehash_hash()
#8 [internal function]: filehash_file_create()
#9 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array()
#10 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(249): Drupal\Core\Extension\ModuleHandler->invokeAll()
#11 /var/www/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(893): Drupal\Core\Entity\EntityStorageBase->invokeHook()
#12 /var/www/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(100): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook()
#13 /var/www/drupal/web/modules/contrib/islandora/src/MediaSource/MediaSourceService.php(271): Drupal\Core\Entity\ContentEntityStorageBase->create()
#14 /var/www/drupal/web/modules/contrib/islandora/src/Controller/MediaSourceController.php(168): Drupal\islandora\MediaSource\MediaSourceService->putToNode()
#15 [internal function]: Drupal\islandora\Controller\MediaSourceController->putToNode()
#16 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#17 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#19 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#20 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#21 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#22 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#23 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#24 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#25 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#26 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#27 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#28 /var/www/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#29 /var/www/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle()
#30 /var/www/drupal/web/core/assets/scaffold/files/index.php(19): Drupal\Core\DrupalKernel->handle()
#31 {main}
.
Severity	Warning
Hostname	172.26.0.6
Operations	
```

**Comment by mjordan** [comment]
I don't see that warning in my Playbook so I am thinking it is specific to your server. Is the warning produced when you add a media to a node manually via the Drupal GUI?

**Comment by dara2** [comment]
Thank you for checking into this! I am not sure if the same error appears when manually adding media, I'll check. But it seems it's not a Workbench issue so I'll close this. Thanks again!
