### ISSUE TITLE
Some update tasks throw KeyError

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#414]
As reported by @dara2 in Slack, some update tasks error out with:

```
Traceback (most recent call last):
 File "./workbench", line 1133, in <module>
  update()
 File "./workbench", line 705, in update
  if entry['value'] not in added:
KeyError: 'value'
```
I am trying to narrow down the problem.

**Comment by mjordan** [comment]
Closing, this is a duplicate of #401.
