### ISSUE TITLE
get_data_from_view failing on node entity references

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#438]
Our content type has a "field_source" field that references other nodes. When get_data_from_view attempts to serialize this field using the `export_csv_term_mode: name` config enabled it [makes an assumption that this entity reference field uses a taxonomy vocabulary](https://github.com/mjordan/islandora_workbench/blob/main/workbench_fields.py#L964) and fails when it can't find a term with that ID (or, even worse, could potentially give a false positive if there happens to be a term with that ID).

E.g. the following stack trace appears when it reaches the following field entry:
Field json:
```json
"field_source": [
  {
    "target_id": 50914,
    "target_type": "node",
    "target_uuid": "0462fb9a-8a91-42b0-a425-caec639bb4ff",
    "url": "/node/50914"
  }
],
```
Stack trace:
```
Traceback (most recent call last):
  File "C:\Users\sshaw\islandora_workbench\workbench", line 1282, in <module>
    get_data_from_view()
  File "C:\Users\sshaw\islandora_workbench\workbench", line 1048, in get_data_from_view
    csv_data = serialize_field_json(config, field_definitions, field_name, node[field_name])
  File "C:\Users\sshaw\islandora_workbench\workbench_utils.py", line 4755, in serialize_field_json
    csv_field_data = serialized_field.serialize(config, field_definitions, field_name, field_data)
  File "C:\Users\sshaw\islandora_workbench\workbench_fields.py", line 964, in serialize
    subvalues.append(vocab_id + ':' + term_name)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

This is a quick fix for the issue:
```diff
diff --git a/workbench_fields.py b/workbench_fields.py
index b1aaccf..5dbbf57 100644
--- a/workbench_fields.py
+++ b/workbench_fields.py
@@ -957,7 +957,7 @@ class EntityReferenceField():

         subvalues = list()
         for subvalue in field_data:
-            if config['export_csv_term_mode'] == 'name':
+            if config['export_csv_term_mode'] == 'name' and subvalue['target_type'] == 'taxonomy_term' :
                 # Output term names.
                 vocab_id = get_term_vocab(config, subvalue['target_id'])
                 term_name = get_term_name(config, subvalue['target_id'])
```

**Comment by mjordan** [comment]
@seth-shaw-unlv thanks for catching this, I'll apply this patch tonight.

**Comment by mjordan** [comment]
Added. Thanks again Seth!
