### ISSUE TITLE
get_data_from_view has an issue with disappearing fields

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#439]
It isn't clear why, but sometimes I have a field (`field_access_terms`) disappear from the node object during serialization of get_data_from_views resulting in a key error:
```
Traceback (most recent call last):
  File "C:\Users\sshaw\islandora_workbench\workbench", line 1283, in <module>
    get_data_from_view()
  File "C:\Users\sshaw\islandora_workbench\workbench", line 1075, in get_data_from_view
    csv_data = serialize_field_json(config, field_definitions, field_name, node[field_name])
KeyError: 'field_access_terms'
```
(That one is actually the second of two instances, after I patched the first.)

The quick fix is to ensure it is there before serialization:
```diff
diff --git a/workbench b/workbench
index 1a2e858..adc9043 100755
--- a/workbench
+++ b/workbench
@@ -1044,7 +1044,7 @@ def get_data_from_view():
             row['title'] = node['title'][0]['value']
             print('Exporting data for node ' + str(node['nid'][0]['value']) + ' "' + node['title'][0]['value'] + '".')
             for field_name in deduped_field_names:
-                if field_name.startswith('field_'):
+                if field_name.startswith('field_') and field_name in node.keys():
                     csv_data = serialize_field_json(config, field_definitions, field_name, node[field_name])
                     row[field_name] = csv_data
             writer.writerow(row)
@@ -1070,7 +1070,7 @@ def get_data_from_view():
                 row['title'] = node['title'][0]['value']
                 print('Exporting data for node ' + str(node['nid'][0]['value']) + ' "' + node['title'][0]['value'] + '".')
                 for field_name in deduped_field_names:
-                    if field_name.startswith('field_'):
+                    if field_name.startswith('field_') and field_name in node:
                         csv_data = serialize_field_json(config, field_definitions, field_name, node[field_name])
                         row[field_name] = csv_data
                 writer.writerow(row)
```

**Comment by mjordan** [comment]
This logic would prevent the KeyError, but I wonder why it's happening?

**Comment by seth-shaw-unlv** [comment]
🤷‍♂️ I haven't been able to discern that. Unfortunately, I'm running low on time to debug further beyond this fix. 😟

Ah, you can remove `.keys()` from that first one; that is redundant.

**Comment by mjordan** [comment]
No problem, I'll apply this patch tonight too.
