### ISSUE TITLE
Error with latest updates

### ISSUE THREAD

**Issue by banetbi** [mjordan/islandora_workbench#463]
When running a check getting the following error. Tried with new files and files that have worked before, still getting same error. CSV and YML attached.
Traceback (most recent call last):
  File "./workbench", line 1270, in <module>
    check_input(config, args)
  File "/home/jcdalton/Development/islandora_workbench/workbench_utils.py", line 1165, in check_input
    if field_definitions[csv_column_header]['handler'] == 'views':
KeyError: 'thumbnail'

YML Config File
task: create
host: "https://digital.libraries.wm.edu"
username: xxxxxxx
password: xxxxxxxx
subdelimiter: ";"
input_csv: /DSLab/Islandora UPLOAD/F234W7A18_DirectoryJCC.csv
allow_adding_terms: true
allow_missing_files: true
additional_files:
 - thumbnail: 38
 - service_file: 32
csv_field_templates:
 - field_display_hints: 30
[F234W7A18_DirectoryJCC.csv](https://github.com/mjordan/islandora_workbench/files/9445920/F234W7A18_DirectoryJCC.csv)

**Comment by mjordan** [comment]
Hi @banetbi, sorry for the delay. Your CSV file looks good, but there are a couple of things that might be causing this. First, can you confirm that the `additional_files` entry in your config file looks like this:

```yaml
additional_files:
 - thumbnail: 38
 - service_file: 32
 ```
(indentation and whitespace are significant).

If that doesn't fix the problem, let me know and I can suggest something else.

**Comment by banetbi** [comment]
Yes, the YAML files are formatted correctly, I guess the formatting didn't
come over when I pasted it.

Thanks!
Justin Dalton
Ad maiorem Dei gloriam

**Comment by mjordan** [comment]
I pushed a fix for #478 a couple days ago. I think that was the same problem you encountered. Can you pull in updates to the main branch and try again?

**Comment by mjordan** [comment]
@banetbi can you confirm this fix worked / didn't work?

**Comment by banetbi** [comment]
It did fix the issue, thanks!
Justin Dalton
Ad maiorem Dei gloriam
