### ISSUE TITLE
Add_media task check fails when file column is empty even when missing files are allowed in config

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#478]
I get this error when running add_media, even though I've included a line in my config saying missing files are okay:
```
islandora@trislandora2-production:/opt/islandora_workbench$ ./workbench --config add_mediaPROD.yml --check
OK, connection to Drupal at https://digitalcollections-i2-prod.tricolib.brynmawr.edu/ verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/ingest/PROD_AddMedia.csv found.
OK, all 10 rows in the CSV file have the same number of columns as there are headers (6).
Traceback (most recent call last):
  File "./workbench", line 1285, in <module>
    check_input(config, args)
  File "/opt/islandora_workbench/workbench_utils.py", line 1482, in check_input
    message = 'CSV row with ID ' + file_check_row[config['id_field']] + ' contains an empty "file" value.'
KeyError: 'id'
islandora@trislandora2-production:/opt/islandora_workbench$
```
My config file is:
```
task: add_media
host: "https://digitalcollections-i2-prod.tricolib.brynmawr.edu/"
username: [myusername]
password: [mypassword]
input_dir: /mnt/ingest
input_csv: PROD_AddMedia.csv
allow_missing_files: true
additional_files:
 - screenshot: 38
 - transcript: 40
 - thumbnail: 39
 - full_text: 228
 ```
 
Based on a conversation with you back in May, I added the following line to my config and that allowed the --check process to complete. But I don't think you meant for this line to be required in add_media tasks permanently, right?
```
id_field: node_id 
```

**Comment by mjordan** [comment]
OK, please pull in changes to main and try again.

**Comment by dara2** [comment]
Sorry - yes! Thank you!
