### ISSUE TITLE
i7import fails when fetch_files=false

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_workbench#479]
My config file:

```
solr_base_url: '[my base url]'
islandora_base_url: 'https://arcabc.ca'
csv_output_path: 'arca_metadata.csv'
obj_directory: '/tmp/objs'
fetch_files: 'False'
get_file_uri: 'True'
log_file_path: 'islandora_content.log'
id_field: 'ID'
id_start_number: 1
namespace: 'vpl'
debug: 'true'
field_pattern: 'dc.*'
```

Running this gets me started, but Workbench fails quickly:

```
Processing 1429.
  [=>                                                                      0.9%                                                                        ]Traceback (most recent call last):
  File "/Users/brandon/islandora_workbench/i7Import/get_islandora_7_content.py", line 99, in <module>
    file = utils.get_i7_asset(row['PID'], datastream)
  File "/Users/brandon/islandora_workbench/i7Import/i7ImportUtilities.py", line 180, in get_i7_asset
    open(obj_file_path, 'wb+').write(obj_download_response.content)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/objs/vpl_992.tiff'
```

The failure is at line 180 of i7ImportUtilities.py... This line is under an IF statement: `if self.config['fetch_files'] and obj_extension:`

As far as I understand, line 180 should not be reached if I had set `fetch_files` to False. [Note I have tried this both lowercase and uppercase to no avail.]

Am I doing something wrong, or is there a bug here?

**Comment by mjordan** [comment]
I'm not sure, but can you try again using YAML values for true/false in your configuration file, like this:

```
solr_base_url: '[my base url]'
islandora_base_url: 'https://arcabc.ca'
csv_output_path: 'arca_metadata.csv'
obj_directory: '/tmp/objs'
fetch_files: false
get_file_uri: true
log_file_path: 'islandora_content.log'
id_field: 'ID'
id_start_number: 1
namespace: 'vpl'
debug: true
field_pattern: 'dc.*'
```

If that doesn't work, let me know.

**Comment by mjordan** [comment]
The config file is straight up YAML, in which `true` is completely different than `"True"`.

> Would it be worth the trouble of adjusting the code so that it accepts the values with and without quotes, or just documenting the need to avoid quotes?

Documenting is the way to go. Attempting to override standard YAML syntax sounds like it would invite all sorts of complexities, and the Workbench code is already far less than clean and simple (in fact, I'm cleaning up the code so that others can help maintain it). I can document this, but thanks for the offer of a PR.

If you're happy, please close this issue. I can add a note to https://mjordan.github.io/islandora_workbench_docs/configuration/ to clarify the YAML syntax.

**Comment by mjordan** [comment]
@bondjimbond can you take a look at https://mjordan.github.io/islandora_workbench_docs/configuration/#configuration-settings to make sure I've updated the documentation adequately?

**Comment by bondjimbond** [comment]
It's understandable, thanks!
