### ISSUE TITLE
--check tests broken

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#561]
#552 broke several tests in tests/islandora_tests_check.py.

**Comment by mjordan** [comment]
Two types of failures:

 - TestCreateAllowMissingFilesWithAdditionalFiles and TestAddMediaAllowMissingWithAdditionalFiles are the tests that are failing. I've marked these tests to be skipped until they can be fixed.

 - Tests that use Google Sheets are also failing in Github Actions due to SSL errors on the Google side., i.e., TestCommentedCsvs, TestGoogleGid, and TestCheckFromGoogleSpreadsheetCheck. They pass when run locally. I've marked these tests to be skipped when run within Github Actions.

The specific error when accessing Google Sheets is:

`SSLError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries 
exceeded with url: 
/spreadsheets/d/13Mw7gtBy1A3ZhYEAlBzmkswIdaZvX18xoRBxfbgxqWc/export?gid=21337685
07&format=csv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer
certificate (_ssl.c:1016)')))`

**Comment by whikloj** [comment]
On OSX I am seeing the Google Sheets errors when testing locally. I'm wondering if the use of `verify` and `REQUEST_CA_BUNDLE` in requests when trying to both test a docker container and Google seems to be part of the issue. Not sure how to resolve it, but seems important to maintain stability.

**Comment by whikloj** [comment]
I was able to get past those errors by un-setting the environment variable for those specific tests.
i.e. I run the tests generally with
```bash
> REQUESTS_CA_BUNDLE=/Users/jaredwhiklo/www/DAM2/isle-dc/certs/rootCA.pem python tests/islandora_tests_check.py
```
and I added
```python
   def test_google_gid(self):
+       temp_bundle = os.environ.get("REQUESTS_CA_BUNDLE", None)
+       if temp_bundle:
+           os.environ["REQUESTS_CA_BUNDLE"] = ""
+
         config_file_path = os.path.join(
              self.current_dir, "assets", "google_gid_test", "gid_0.yml"
         )
```
and 
```python
+        if temp_bundle:
+            os.environ["REQUESTS_CA_BUNDLE"] = temp_bundle
```
around the google sheet tests.

So when I previously got a huge error message that ended with
```bash
SSLError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /spreadsheets/d/13Mw7gtBy1A3ZhYEAlBzmkswIdaZvX18xoRBxfbgxqWc/export?gid=0&format=csv 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))
ERow 2 (ID 02) of the CSV file "tests/assets/header_column_mismatch_test/metadata.csv" has more columns (6) than there are headers (5).
......Error: Value in field "field_linked_agent" in row with ID 1127680 (relatorsaut:1000) does not use the structure required for typed relation fields.
.Error: Term URI "http://example.com" used in CSV column "field_linked_agent" row with ID 02 does not match any terms.
..Error: Term names in CSV field "field_linked_agent" require a vocabulary namespace; CSV value "Newman, Alfred E." in row with ID 02 does not have one.
...
======================================================================
ERROR: test_create_from_google_spreadsheet_check (__main__.TestCheckFromGoogleSpreadsheetCheck)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/islandora_tests_check.py", line 70, in setUp
    output = subprocess.check_output(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jaredwhiklo/www/DAM2/islandora_workbench/workbench', '--config', '/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/assets/check_test/google_sheet.yml', '--check']' returned non-zero exit status 1.

======================================================================
ERROR: test_commented_csv (__main__.TestCommentedCsvs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/islandora_tests_check.py", line 1527, in test_commented_csv
    output = subprocess.check_output(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jaredwhiklo/www/DAM2/islandora_workbench/workbench', '--config', '/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/assets/commented_csvs_test/google_sheets.yml', '--check']' returned non-zero exit status 1.

======================================================================
ERROR: test_google_gid (__main__.TestGoogleGid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/islandora_tests_check.py", line 95, in test_google_gid
    output = subprocess.check_output(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.22_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jaredwhiklo/www/DAM2/islandora_workbench/workbench', '--config', '/Users/jaredwhiklo/www/DAM2/islandora_workbench/tests/assets/google_gid_test/gid_0.yml', '--check']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 36 tests in 597.812s

FAILED (errors=3, skipped=3)
```
now I get
```bash
> REQUESTS_CA_BUNDLE=/Users/jaredwhiklo/www/DAM2/isle-dc/certs/rootCA.pem python tests/islandora_tests_check.py
...sss...............ERROR:root:Workbench could not connect to https://somebadhost.org while requesting "https://somebadhost.org/islandora_workbench_integration/node_actions/entity_display/node/islandora_object".
ERROR:root:HTTPSConnectionPool(host='somebadhost.org', port=443): Max retries exceeded with url: /islandora_workbench_integration/node_actions/entity_display/node/islandora_object (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10ff91a00>: Failed to resolve 'somebadhost.org' ([Errno 8] nodename nor servname provided, or not known)"))
Error: Workbench could not connect to https://somebadhost.org while requesting "https://somebadhost.org/islandora_workbench_integration/node_actions/entity_display/node/islandora_object".
.Error: Value in field "field_coordinates" in row with ID 1127680 (+43.45-123.17) is not a valid lat,long pair.
..Row 2 (ID 02) of the CSV file "tests/assets/header_column_mismatch_test/metadata.csv" has more columns (6) than there are headers (5).
......Error: Value in field "field_linked_agent" in row with ID 1127680 (relatorsaut:1000) does not use the structure required for typed relation fields.
.Error: Term URI "http://example.com" used in CSV column "field_linked_agent" row with ID 02 does not match any terms.
..Error: Term names in CSV field "field_linked_agent" require a vocabulary namespace; CSV value "Newman, Alfred E." in row with ID 02 does not have one.
...
----------------------------------------------------------------------
Ran 36 tests in 642.524s

OK (skipped=3)
```

**Comment by mjordan** [comment]
All tests are functional as of d78afad9d5031ca82ff09599882f2c997cbdaf8c.
