### ISSUE TITLE
TypeError: clean_csv_values() missing 1 required positional argument: 'row

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#568]
I have the following iw:
```
git log -1
commit e659616edb3821517ebb7920edc5964e423f15b5 (HEAD -> main, origin/main, origin/HEAD)
Author: Mark Jordan <mjordan@sfu.ca>
Date:   Fri Feb 24 06:40:39 2023 -0800

    Address #567.
```

Getting the following issue when trying to ingest records.
```
Traceback (most recent call last):
  File "./workbench", line 1368, in <module>
    check_input(config, args)
  File "/home/nat/tools/iw_8feb2023/islandora_workbench/workbench_utils.py", line 1337, in check_input
    csv_data = get_csv_data(config)
  File "/home/nat/tools/iw_8feb2023/islandora_workbench/workbench_utils.py", line 3492, in get_csv_data
    row = clean_csv_values(row)
TypeError: clean_csv_values() missing 1 required positional argument: 'row'
```

The ingest config:

```
task: create
host: "https://islandora.traefik.me"
username: admin
password: password
input_csv: 'https://docs.google.com/spreadsheets/d/1DV0Ka0ZafZq3RgCn0x_AetFtlmnMuNFltzck2QL0ApY/edit?usp=sharing'
google_sheets_gid: 994664908
content_type: islandora_object
subdelimiter: "|"
allow_adding_terms: true
input_dir: repo_islandora_demo_objects
ignore_csv_columns: ["Transcript", "Supplemental_PDF", "field_display_hints"]
```

Looks like we need to pass the config variable to clean_csv_values function.

**Comment by mjordan** [comment]
Sorry, my bad, I'll fix ASAP.

**Comment by mjordan** [comment]
@Natkeeran please pull in updates to main and try again.

**Comment by Natkeeran** [comment]
@mjordan 

Seems good.  Thank you for the quick response.

**Comment by mjordan** [comment]
Thanks for confirming. Sorry about that.
