### ISSUE TITLE
Import frequently crashing due to IncompleteRead

### ISSUE THREAD

**Issue by banetbi** [mjordan/islandora_workbench#594]
Frequently receiving the following error, seems to be involving bad connection, but doesn't report anything in the logs and can't recover from the error.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 685, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 689, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./workbench", line 1344, in <module>
    create()
  File "./workbench", line 224, in create
    node_response = issue_request(config, 'POST', node_endpoint, node_headers, node, None)
  File "/home/jcdalton/islandora_workbench/workbench_utils.py", line 228, in issue_request
    response = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cache/session.py", line 159, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cache/session.py", line 206, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cache/session.py", line 230, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by mjordan** [comment]
Can you pull in updates to the `main` branch and try again? Doing that probably won't fix the problem but there are changes since the version you are using that make exceptions easier to read.

**Comment by mjordan** [comment]
Also, knowing if your Islandora is ISLE, Playbook, or custom build will help figure out what's going on. Thanks.

**Comment by banetbi** [comment]
Here is the updated error:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3/dist-packages/urllib3/response.py:685 in _update_chunk_length                   │
│                                                                                                  │
│   682 │   │   line = self._fp.fp.readline()                                                      │
│   683 │   │   line = line.split(b";", 1)[0]                                                      │
│   684 │   │   try:                                                                               │
│ ❱ 685 │   │   │   self.chunk_left = int(line, 16)                                                │
│   686 │   │   except ValueError:                                                                 │
│   687 │   │   │   # Invalid chunked protocol response, abort.                                    │
│   688 │   │   │   self.close()                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3/dist-packages/urllib3/response.py:425 in _error_catcher                         │
│                                                                                                  │
│   422 │   │                                                                                      │
│   423 │   │   try:                                                                               │
│   424 │   │   │   try:                                                                           │
│ ❱ 425 │   │   │   │   yield                                                                      │
│   426 │   │   │                                                                                  │
│   427 │   │   │   except SocketTimeout:                                                          │
│   428 │   │   │   │   # FIXME: Ideally we'd like to include the url in the ReadTimeoutError bu   │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/urllib3/response.py:752 in read_chunked                           │
│                                                                                                  │
│   749 │   │   │   │   return                                                                     │
│   750 │   │   │                                                                                  │
│   751 │   │   │   while True:                                                                    │
│ ❱ 752 │   │   │   │   self._update_chunk_length()                                                │
│   753 │   │   │   │   if self.chunk_left == 0:                                                   │
│   754 │   │   │   │   │   break                                                                  │
│   755 │   │   │   │   chunk = self._handle_chunk(amt)                                            │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/urllib3/response.py:689 in _update_chunk_length                   │
│                                                                                                  │
│   686 │   │   except ValueError:                                                                 │
│   687 │   │   │   # Invalid chunked protocol response, abort.                                    │
│   688 │   │   │   self.close()                                                                   │
│ ❱ 689 │   │   │   raise httplib.IncompleteRead(line)                                             │
│   690 │                                                                                          │
│   691 │   def _handle_chunk(self, amt):                                                          │
│   692 │   │   returned_chunk = None                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3/dist-packages/requests/models.py:750 in generate                                │
│                                                                                                  │
│   747 │   │   │   # Special case for urllib3.                                                    │
│   748 │   │   │   if hasattr(self.raw, 'stream'):                                                │
│   749 │   │   │   │   try:                                                                       │
│ ❱ 750 │   │   │   │   │   for chunk in self.raw.stream(chunk_size, decode_content=True):         │
│   751 │   │   │   │   │   │   yield chunk                                                        │
│   752 │   │   │   │   except ProtocolError as e:                                                 │
│   753 │   │   │   │   │   raise ChunkedEncodingError(e)                                          │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/urllib3/response.py:560 in stream                                 │
│                                                                                                  │
│   557 │   │   │   'content-encoding' header.                                                     │
│   558 │   │   """                                                                                │
│   559 │   │   if self.chunked and self.supports_chunked_reads():                                 │
│ ❱ 560 │   │   │   for line in self.read_chunked(amt, decode_content=decode_content):             │
│   561 │   │   │   │   yield line                                                                 │
│   562 │   │   else:                                                                              │
│   563 │   │   │   while not is_fp_closed(self._fp):                                              │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/urllib3/response.py:781 in read_chunked                           │
│                                                                                                  │
│   778 │   │   │                                                                                  │
│   779 │   │   │   # We read everything; close the "file".                                        │
│   780 │   │   │   if self._original_response:                                                    │
│ ❱ 781 │   │   │   │   self._original_response.close()                                            │
│   782 │                                                                                          │
│   783 │   def geturl(self):                                                                      │
│   784 │   │   """                                                                                │
│                                                                                                  │
│ /usr/lib/python3.8/contextlib.py:131 in __exit__                                                 │
│                                                                                                  │
│   128 │   │   │   │   # tell if we get the same exception back                                   │
│   129 │   │   │   │   value = type()                                                             │
│   130 │   │   │   try:                                                                           │
│ ❱ 131 │   │   │   │   self.gen.throw(type, value, traceback)                                     │
│   132 │   │   │   except StopIteration as exc:                                                   │
│   133 │   │   │   │   # Suppress StopIteration *unless* it's the same exception that             │
│   134 │   │   │   │   # was passed to throw().  This prevents a StopIteration                    │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/urllib3/response.py:443 in _error_catcher                         │
│                                                                                                  │
│   440 │   │   │                                                                                  │
│   441 │   │   │   except (HTTPException, SocketError) as e:                                      │
│   442 │   │   │   │   # This includes IncompleteRead.                                            │
│ ❱ 443 │   │   │   │   raise ProtocolError("Connection broken: %r" % e, e)                        │
│   444 │   │   │                                                                                  │
│   445 │   │   │   # If no exception is thrown, we should avoid cleaning up                       │
│   446 │   │   │   # unnecessarily.                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jcdalton/islandora_workbench/./workbench:1376 in <module>                                  │
│                                                                                                  │
│   1373                                                                                           │
│   1374 try:                                                                                      │
│   1375 │   if config['task'] == 'create':                                                        │
│ ❱ 1376 │   │   create()                                                                          │
│   1377 │   if config['task'] == 'update':                                                        │
│   1378 │   │   update()                                                                          │
│   1379 │   if config['task'] == 'delete':                                                        │
│                                                                                                  │
│ /home/jcdalton/islandora_workbench/./workbench:238 in create                                     │
│                                                                                                  │
│    235 │   │                                                                                     │
│    236 │   │   node_headers = {'Content-Type': 'application/json'}                               │
│    237 │   │   node_endpoint = '/node?_format=json'                                              │
│ ❱  238 │   │   node_response = issue_request(config, 'POST', node_endpoint, node_headers, node,  │
│    239 │   │   if node_response.status_code == 201:                                              │
│    240 │   │   │   node_uri = node_response.headers['location']                                  │
│    241 │   │   │   returned_node = json.loads(node_response.text)                                │
│                                                                                                  │
│ /home/jcdalton/islandora_workbench/workbench_utils.py:231 in issue_request                       │
│                                                                                                  │
│    228 │   │   │   logging.info(headers)                                                         │
│    229 │   │   if config['log_json'] is True:                                                    │
│    230 │   │   │   logging.info(json)                                                            │
│ ❱  231 │   │   response = requests.post(                                                         │
│    232 │   │   │   url,                                                                          │
│    233 │   │   │   allow_redirects=config['allow_redirects'],                                    │
│    234 │   │   │   verify=config['secure_ssl_only'],                                             │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/api.py:116 in post                                       │
│                                                                                                  │
│   113 │   :rtype: requests.Response                                                              │
│   114 │   """                                                                                    │
│   115 │                                                                                          │
│ ❱ 116 │   return request('post', url, data=data, json=json, **kwargs)                            │
│   117                                                                                            │
│   118                                                                                            │
│   119 def put(url, data=None, **kwargs):                                                         │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/api.py:60 in request                                     │
│                                                                                                  │
│    57 │   # avoid leaving sockets open which can trigger a ResourceWarning in some               │
│    58 │   # cases, and look like a memory leak in others.                                        │
│    59 │   with sessions.Session() as session:                                                    │
│ ❱  60 │   │   return session.request(method=method, url=url, **kwargs)                           │
│    61                                                                                            │
│    62                                                                                            │
│    63 def get(url, params=None, **kwargs):                                                       │
│                                                                                                  │
│ /home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cach │
│ e/session.py:159 in request                                                                      │
│                                                                                                  │
│   156 │   │   """                                                                                │
│   157 │   │   headers = set_request_headers(headers, expire_after, only_if_cached, refresh, fo   │
│   158 │   │   with patch_form_boundary() if kwargs.get('files') else nullcontext():              │
│ ❱ 159 │   │   │   return super().request(method, url, *args, headers=headers, **kwargs)  # typ   │
│   160 │                                                                                          │
│   161 │   def send(                                                                              │
│   162 │   │   self,                                                                              │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/sessions.py:533 in request                               │
│                                                                                                  │
│   530 │   │   │   'allow_redirects': allow_redirects,                                            │
│   531 │   │   }                                                                                  │
│   532 │   │   send_kwargs.update(settings)                                                       │
│ ❱ 533 │   │   resp = self.send(prep, **send_kwargs)                                              │
│   534 │   │                                                                                      │
│   535 │   │   return resp                                                                        │
│   536                                                                                            │
│                                                                                                  │
│ /home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cach │
│ e/session.py:206 in send                                                                         │
│                                                                                                  │
│   203 │   │   elif actions.resend_request:                                                       │
│   204 │   │   │   response = self._resend(request, actions, cached_response, **kwargs)  # type   │
│   205 │   │   elif actions.send_request:                                                         │
│ ❱ 206 │   │   │   response = self._send_and_cache(request, actions, cached_response, **kwargs)   │
│   207 │   │   else:                                                                              │
│   208 │   │   │   response = cached_response  # type: ignore  # Guaranteed to be non-None by t   │
│   209                                                                                            │
│                                                                                                  │
│ /home/jcdalton/.local/lib/python3.8/site-packages/requests_cache-1.0.0a1-py3.8.egg/requests_cach │
│ e/session.py:230 in _send_and_cache                                                              │
│                                                                                                  │
│   227 │   │   If applicable, also handle conditional requests.                                   │
│   228 │   │   """                                                                                │
│   229 │   │   request = actions.update_request(request)                                          │
│ ❱ 230 │   │   response = super().send(request, **kwargs)                                         │
│   231 │   │   actions.update_from_response(response)                                             │
│   232 │   │                                                                                      │
│   233 │   │   if not actions.skip_write:                                                         │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/sessions.py:686 in send                                  │
│                                                                                                  │
│   683 │   │   │   │   pass                                                                       │
│   684 │   │                                                                                      │
│   685 │   │   if not stream:                                                                     │
│ ❱ 686 │   │   │   r.content                                                                      │
│   687 │   │                                                                                      │
│   688 │   │   return r                                                                           │
│   689                                                                                            │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/models.py:828 in content                                 │
│                                                                                                  │
│   825 │   │   │   if self.status_code == 0 or self.raw is None:                                  │
│   826 │   │   │   │   self._content = None                                                       │
│   827 │   │   │   else:                                                                          │
│ ❱ 828 │   │   │   │   self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''     │
│   829 │   │                                                                                      │
│   830 │   │   self._content_consumed = True                                                      │
│   831 │   │   # don't need to release the connection; that's been handled by urllib3             │
│                                                                                                  │
│ /usr/lib/python3/dist-packages/requests/models.py:753 in generate                                │
│                                                                                                  │
│   750 │   │   │   │   │   for chunk in self.raw.stream(chunk_size, decode_content=True):         │
│   751 │   │   │   │   │   │   yield chunk                                                        │
│   752 │   │   │   │   except ProtocolError as e:                                                 │
│ ❱ 753 │   │   │   │   │   raise ChunkedEncodingError(e)                                          │
│   754 │   │   │   │   except DecodeError as e:                                                   │
│   755 │   │   │   │   │   raise ContentDecodingError(e)                                          │
│   756 │   │   │   │   except ReadTimeoutError as e:                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by banetbi** [comment]
After doing some diagnostics on the server, there was an issue with the islandora config that was causing the connections to drop. Thanks for looking into this!
