### ISSUE TITLE
Github actions are failing for Python 3.8

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#822]
Some time after September 11, the `edtf-validate` library is causing [this Github action](https://github.com/mjordan/islandora_workbench/actions/runs/10865051865/job/30275782759) to fail for Python 3.8:

```
Run python tests/unit_tests.py
Traceback (most recent call last):
  File "tests/unit_tests.py", line 12, in <module>
    import workbench_utils
  File "/home/runner/work/islandora_workbench/islandora_workbench/workbench_utils.py", line 28, in <module>
    import edtf_validate.valid_edtf
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/edtf_validate-2.0.0-py3.8.egg/edtf_validate/valid_edtf.py", line 16, in <module>
    from pyparsing import Optional, oneOf, OneOrMore, ZeroOrMore, Empty, StringStart, StringEnd
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyparsing-3.2.0b1-py3.8.egg/pyparsing/__init__.py", line 129, in <module>
    from .util import *
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyparsing-3.2.0b1-py3.8.egg/pyparsing/util.py", line 14, in <module>
    class __config_flags:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyparsing-3.2.0b1-py3.8.egg/pyparsing/util.py", line 17, in __config_flags
    _all_names: list[str] = []
TypeError: 'type' object is not subscriptable
Error: Process completed with exit code 1.
```

Strange thing is, this this library hasn't been updated in 3 years. Also, the same action has been running successfully since Sept. 11. Something in the Github environment must have changed.

**Comment by berrytern** [comment]
Hi, I am openning a PR...

**Comment by mjordan** [comment]
Very good - thank you very much for helping with that!
