### ISSUE TITLE
TestAdditionalFilesCreate tests are failing

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#826]
```
mark@mark-XPS-9320:~/hacking/islandora_workbench$ python tests/islandora_tests.py TestAdditionalFilesCreate
EE
======================================================================
ERROR: test_media_creation (__main__.TestAdditionalFilesCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/hacking/islandora_workbench/tests/islandora_tests.py", line 923, in setUp
    media_list_json = json.loads(media_list_response.text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_media_use_tids (__main__.TestAdditionalFilesCreate)
Doesn't associate media use terms to nodes, but at least it confirms that the intended
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/hacking/islandora_workbench/tests/islandora_tests.py", line 923, in setUp
    media_list_json = json.loads(media_list_response.text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 2 tests in 60.840s

FAILED (errors=2)
```

**Comment by mjordan** [comment]
HTTP response code is suddenly 403....

**Comment by mjordan** [comment]
Fixed. Change introduced in #807 conflicted with getting the node ID of the test node.
